# Generated by Django 2.2.22 on 2021-05-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valf_montaj',
            name='personel',
        ),
    ]
