# Generated by Django 2.2.22 on 2021-05-09 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_remove_valf_montaj_personel'),
    ]

    operations = [
        migrations.AddField(
            model_name='valf_montaj',
            name='kurlenme_personel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kurlenme_personel', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valf_montaj',
            name='montaj_personel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='montaj_personel', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valf_montaj',
            name='montaj_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
