# Generated by Django 2.2.22 on 2021-05-09 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210509_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valf_montaj',
            name='kurlenme_personel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kurlenme_personel', to=settings.AUTH_USER_MODEL),
        ),
    ]
