# Generated by Django 2.2.22 on 2021-05-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210510_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valf_test',
            name='uygunluk',
        ),
        migrations.AddField(
            model_name='valf_test',
            name='uygun',
            field=models.BooleanField(default=False),
        ),
    ]
