# Generated by Django 2.2.22 on 2021-05-10 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210510_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='valf',
            name='valf_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Valf_test'),
            preserve_default=False,
        ),
    ]
