# Generated by Django 2.2.22 on 2021-05-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_valf_valf_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valf',
            name='valf_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Valf_test'),
        ),
    ]
