# Generated by Django 2.2.22 on 2021-05-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210510_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valf_govde',
            name='kayit_tarihi',
        ),
        migrations.RemoveField(
            model_name='valf_govde',
            name='kurlenme_bitis',
        ),
        migrations.RemoveField(
            model_name='valf_govde',
            name='personel',
        ),
        migrations.RemoveField(
            model_name='valf_govde',
            name='valf',
        ),
    ]
